# 从线程抛出异常

## 窗口类.cpp

文件开头声明一个全局变量

```
std::exception_ptr errorPtr = NULL;
```

判断全局变量是否为null，如果不是重新抛出异常捕获它，然后异常处理

```
if (errorPtr)
{
    try
    {
        std::rethrow_exception(errorPtr);
    }
    catch (const std::exception& ex)
    {
        QMessageBox::critical(this, "error", ex.what());
        errorPtr = NULL;
    }
}
else
{ }
```

## 线程类.cpp

文件开头声明一个外部变量

```
extern std::exception_ptr errorPtr;
```

run()函数中

```
try
{
  function ()//功能函数里面可以抛出任何异常
}
catch (...)
{
    errorPtr = std::current_exception();        
}
```

## 功能类.cpp

任意抛出异常

```
if (ret < 0)
{
      throw std::runtime_error(“...”);
      return;
 }
```

## QT中可以直接用信号槽实现

在qt线程类中emit错误信号后return，在界面类创建一个处理错误的槽函数，再连接界面对象和线程对象的错误信号槽
